import fs from "fs";

const MAX_LENGTH = 34; // from max-text-len.py News.srt max length was 38 character. We keep a bit of extra space for corrections

export type InputEntry = { word: string; start: number; end: number };
export type Entry = { text: string; start: number; end: number };

export const createSRTData = (words: InputEntry[]): Entry[] => {
  const result: Entry[] = [];
  let currentGroup: Entry | null = null;

  for (const word of words) {
    if (!currentGroup) {
      const { word: inputWord, start, end } = word;
      currentGroup = { text: inputWord, start, end };
    } else if (currentGroup.text.length + word.word.length + 1 <= MAX_LENGTH) {
      currentGroup.text += " " + word.word;
      currentGroup.end = word.end;
    } else {
      result.push(currentGroup);
      const { word: inputWord, start, end } = word;
      currentGroup = { text: inputWord, start, end };
    }
  }

  if (currentGroup) {
    result.push(currentGroup);
  }

  return result;
};

export const groupLines = (data: Entry[]) => {
  const entries: Entry[] = [];
  for (let i = 0; i < data.length; i += 2) {
    const currentEntry = data[i];
    const nextEntry = i + 1 < data.length ? data[i + 1] : null;

    // Ensure text values are defined or default to empty strings
    const currentText = currentEntry?.text || "";
    const nextText = nextEntry?.text || "";

    entries.push({
      text: currentText + (nextEntry ? "\n" + nextText : ""),
      start: currentEntry.start,
      end: nextEntry ? nextEntry.end : currentEntry.end,
    });
  }

  return entries;
};

const srtTimestamp = (ms: number, separator: string = ",") => {
  const date = new Date(ms * 1000);

  const hours = date.getHours().toString().padStart(2, "0");
  const minutes = date.getMinutes().toString().padStart(2, "0");
  const seconds = date.getSeconds().toString().padStart(2, "0");
  const milliseconds = date.getMilliseconds().toString().padStart(3, "0");

  return `${hours}:${minutes}:${seconds}${separator}${milliseconds}`;
};

export const formatSRT = (entries: Entry[]) => {
  let out = "";
  for (const [index, entry] of entries.entries()) {
    out += `${index}
${srtTimestamp(entry.start)} --> ${srtTimestamp(entry.end)}
<font color=#ffffff>${entry.text}</font>

`;
  }
  return out;
};

export const createSRTFile = async (filepath: string, entries: Entry[]) => {
  if (fs.existsSync(filepath)) {
    fs.unlinkSync(filepath);
  }

  const stream = fs.createWriteStream(filepath, { flags: "a" });
  for (const [index, entry] of entries.entries()) {
    stream.write(`${index}
${srtTimestamp(entry.start)} --> ${srtTimestamp(entry.end)}
<font color=#ffffff>${entry.text}</font>

`);
  }
  stream.end();
};

export const formatASS = (entries: Entry[]): string => {
  let out = `[Script Info]
Title: Generated Subtitle
Original Script: Generated by transcription
ScriptType: v4.00+
Collisions: Normal
PlayDepth: 0
WrapStyle: 0
ScaledBorderAndShadow: yes

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial,20,&H00FFFFFF,&H00FFFFFF,&H00000000,&H64000000,-1,0,1,2,2,2,10,10,10,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
`;

  for (const entry of entries) {
    out += `Dialogue: 0,${srtTimestamp(entry.start, ".")},${srtTimestamp(
      entry.end,
      ".",
    )},Default,,0,0,0,,{\\c&HFFFFFF&}${entry.text.replace(/\n/g, "\\N")}\n`;
  }

  return out;
};
