[build]
  functions = "functions" 
  publish = "dist"         

[functions]
  node_bundler = "esbuild"
  included_files = ["bin/osx/**"]

  [functions."transcribeAudio-background"]
    timeout = 900 
    memory = 1024

  [functions.max_lambda_size]
    value = "50mb"