[build]
  functions = "functions" 
  publish = "dist"     

[dev]
  command = "pnpm run dev"    

[functions]
  node_bundler = "esbuild"
  directory = "netlify/functions"
  included_files = ["bin/osx/**", "bin/linux/**"]

  [functions."transcribeAudio-background"]
    timeout = 900 
    memory = 1024

  [functions.max_lambda_size]
    value = "50mb"