/** @type {import('tailwindcss').Config} */
const colors = require("tailwindcss/colors");

export default {
  content: ["./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue,svg}"],
  theme: {
    fontFamily: {
      sans: [
        "Inter",
        "ui-sans-serif",
        "system-ui",
        "sans-serif",
        '"Apple Color Emoji"',
        '"Segoe UI Emoji"',
        '"Segoe UI Symbol"',
        '"Noto Color Emoji"',
      ],
      serif: [
        "ui-serif",
        "Georgia",
        "Cambria",
        '"Times New Roman"',
        "Times",
        "serif",
      ],
      mono: [
        "ui-monospace",
        "SFMono-Regular",
        "Menlo",
        "Monaco",
        "Consolas",
        '"Liberation Mono"',
        '"Courier New"',
        "monospace",
      ],
    },
    extend: {
      backgroundImage: {
        "blue-design": "url('/img/aibox-login-background.svg')",
      },
      keyframes: {
        "slide-in": {
          "0%": { transform: "scale(0.95)", opacity: "0" },
          "100%": { transform: "scale(1)", opacity: "1" },
        },
        "slide-out": {
          "0%": { transform: "scale(1)", opacity: "1" },
          "100%": { transform: "scale(0.95)", opacity: "0" },
        },
        typing: {
          "0%": {
            width: "0%",
            visibility: "hidden",
          },
          "50%": {
            width: "100%",
          },
        },
        blink: {
          "0%": {
            borderColor: "transparent",
          },
          "50%": {
            borderColor: "white",
          },
        },
      },
      animation: {
        "slide-in": "slide-in 0.5s ease-in-out forwards",
        "slide-out": "slide-out 0.5s ease-in-out forwards",
        typing: "typing 2s steps(10) infinite alternate, blink .7s infinite",
      },
    },
  },
  daisyui: {
    themes: [
      "light",
      "dark",
      "cupcake",
      "bumblebee",
      "emerald",
      "corporate",
      "synthwave",
      "retro",
      "cyberpunk",
      "valentine",
      "halloween",
      "garden",
      "forest",
      "aqua",
      "lofi",
      "pastel",
      "fantasy",
      "wireframe",
      "black",
      "luxury",
      "dracula",
      "cmyk",
      "autumn",
      "business",
      "acid",
      "lemonade",
      "night",
      "coffee",
      "winter",
      "dim",
      "nord",
      "sunset",
      {
        somedia: {
          primary: "#0068a5",
          "primary-focus": "#3730A3",
          "primary-content": "#C7D2FE",
          secondary: "#EC4899",
          "secondary-focus": "#DB2777",
          "secondary-content": "#FBCFE8",
          accent: "#2DD4BF",
          "accent-focus": "#14B8A6",
          "accent-content": "#134E4A",
          neutral: "#374151",
          "neutral-focus": "#1F2937",
          "neutral-content": "#D7DDE4",
          "base-100": "#F3F4F6",
          "base-200": "#E5E7EB",
          "base-300": "#D1D5DB",
          "base-content": "#1F2937",
          info: "#06B6D4",
          "info-content": "#164E63",
          success: "#4ADE80",
          "success-content": "#14532D",
          warning: "#EAB308",
          "warning-content": "#713F12",
          error: "#F87171",
          "error-content": "#7F1D1D",
        },
      },
    ],
  },
  darkMode: "selector",
  plugins: [require("daisyui")],
};
