<!-- svelte-ignore a11y_no_noninteractive_tabindex -->
<!-- svelte-ignore a11y_label_has_associated_control -->
<script>
  let prompt = "";
  let imageUrl = "";
  let loading = false;
  let error = "";
  let size = "1024x1024";
  let quality = "standard";

  const sizeOptions = [
    { value: "1024x1024", label: "1024x1024" },
    { value: "1792x1024", label: "1792x1024" },
    { value: "1024x1792", label: "1024x1792" },
  ];

  const qualityOptions = [
    { value: "standard", label: "Standard" },
    { value: "hd", label: "HD" },
  ];

  // Mock usage stats (replace with actual API call if available)
  let usageStats = {
    today: 22,
    thisMonth: 30,
    available: 3,
  };

  async function generateImage() {
    loading = true;
    error = "";
    imageUrl = "";

    const formData = new FormData();
    formData.append("prompt", prompt);
    formData.append("size", size);
    formData.append("quality", quality);

    try {
      const response = await fetch("/api/generate-image-openai", {
        method: "POST",
        body: formData,
      });

      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.error || "Something went wrong");
      }

      imageUrl = data.imageUrl;
    } catch (err) {
      error = err.message;
    } finally {
      loading = false;
    }
  }

  function downloadImage() {
    if (imageUrl) {
      const link = document.createElement("a");
      link.href = imageUrl;
      link.download = "generated-image.png";
      link.target = "_blank";
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
    }
  }
</script>

<div class="min-h-screen bg-gray-100 flex items-center justify-center p-4">
  <div class="w-full max-w-4xl bg-white rounded-lg shadow-lg p-6">
    <h1 class="text-2xl font-bold text-gray-900 mb-2">Create DALL-E Image</h1>
    <p class="text-sm text-gray-600 mb-4">
      Create images from the latest DALL-E 3 Model
    </p>

    <form on:submit|preventDefault={generateImage} class="space-y-4">
      <div>
        <textarea
          bind:value={prompt}
          placeholder="Describe your picture"
          disabled={loading}
          class="textarea textarea-bordered w-full h-24 rounded-lg focus:outline-none focus:ring-2 focus:ring-purple-500"
        ></textarea>
      </div>

      <div class="flex space-x-4">
        <div class="flex-1">
          <label class="block text-sm font-medium text-gray-700 mb-1"
            >Image Size</label
          >
          <div class="dropdown w-full">
            <label
              tabindex="0"
              class="select select-bordered w-full rounded-lg"
            >
              {sizeOptions.find((opt) => opt.value === size)?.label ||
                "Select Size"}
            </label>
            <ul
              tabindex="0"
              class="dropdown-content menu p-2 shadow bg-base-100 rounded-box w-full"
            >
              {#each sizeOptions as option}
                <li>
                  <button type="button" on:click={() => (size = option.value)}>
                    {option.label}
                  </button>
                </li>
              {/each}
            </ul>
          </div>
        </div>

        <div class="flex-1">
          <label class="block text-sm font-medium text-gray-700 mb-1"
            >Image Quality</label
          >
          <div class="dropdown w-full">
            <label
              tabindex="0"
              class="select select-bordered w-full rounded-lg"
            >
              {qualityOptions.find((opt) => opt.value === quality)?.label ||
                "Select Quality"}
            </label>
            <ul
              tabindex="0"
              class="dropdown-content menu p-2 shadow bg-base-100 rounded-box w-full"
            >
              {#each qualityOptions as option}
                <li>
                  <button
                    type="button"
                    on:click={() => (quality = option.value)}
                  >
                    {option.label}
                  </button>
                </li>
              {/each}
            </ul>
          </div>
        </div>
      </div>

      <button
        type="submit"
        disabled={loading}
        class="btn btn-primary w-40 rounded-lg"
      >
        {loading ? "Generating..." : "Generate Image"}
      </button>
    </form>

    {#if error}
      <p class="text-error text-center mt-4">{error}</p>
    {/if}

    {#if imageUrl}
      <div class="mt-6">
        <img
          src={imageUrl}
          alt="Generated by DALL-E 3"
          class="w-full rounded-lg shadow-lg"
        />
        <button
          on:click={downloadImage}
          class="btn btn-primary w-40 rounded-lg mt-4"
        >
          Download
        </button>
      </div>
    {/if}

    <div class="mt-6 card bg-base-100 shadow-lg p-4 w-64 ml-auto">
      <h3 class="text-sm font-semibold text-gray-700">Current Usage</h3>
      <p class="text-sm text-gray-600 mt-2">Today: {usageStats.today} images</p>
      <p class="text-sm text-gray-600">
        This month: {usageStats.thisMonth} images
      </p>
      <p class="text-sm text-gray-600">
        Available: {usageStats.available} images
      </p>
    </div>
  </div>
</div>

<style>
  .btn-primary {
    background-color: #6b46c1; /* Purple color from the UI */
    border-color: #6b46c1;
  }
  .btn-primary:hover {
    background-color: #553c9a; /* Darker purple on hover */
    border-color: #553c9a;
  }
</style>
